[package]
name = "elusion"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "43.0.0"
arrow = "53.3.0"
tokio = { version = "1.0", features = ["rt-multi-thread"] }
futures = "0.3.31"
chrono = "0.4.38"
regex = "1.11.1"
encoding_rs = "0.8.35"
uuid = { version = "1.4", features = ["v4"] }
env_logger = "0.11.5"
log = "0.4.22"

# [profile.release]
# lto = true
# codegen-units = 1