[package]
name = "elusion"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "43.0.0"
arrow = "53.3.0"
tokio = { version = "1.0", features = ["rt-multi-thread"] }
futures = "0.3.31"
chrono = "0.4.38"
regex = "1.11.1"
# [profile.release]
# lto = true
# codegen-units = 1